
- name: Web Server Playbook
  gather_facts: false
  hosts: all
  become: yes
  tasks:
           - name: "apt-get update"
             apt:
                     update_cache: yes
                     cache_valid_time: 3600

           - name: Install AWS CLI
             apt:
                    name: awscli
                    state: present

           - name: "install nginx"
             apt:
                     name: ['nginx']
                     state: latest

           - name: "start nginx"
             systemd:
                     state: started
                     name: nginx
           
           - name: "Check SSH key"
             stat:
                     path: /home/ubuntu/jenkins_key/jenkins.pub
             register: ssh_exist          

           - name: "Download Jenkins server SSH public key"
             shell:
                     cmd: aws s3 cp s3://sshbucket-0408/key/id_rsa.pub /home/ubuntu/jenkins_key/jenkins.pub
             when: not ssh_exist.stat.exists

           - name: "Add Jenkins server key to Auth key"
             shell:
                     cmd: cat /home/ubuntu/jenkins_key/jenkins.pub >> /home/ubuntu/.ssh/authorized_keys 
             when: not ssh_exist.stat.exists
